apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  labels:
    app: employees
spec:
  template:
    metadata:
      name: employees-pod
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: registry.w3pro.net/employees:0.0.1
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: employees-config
              key: KEYCLOAK_AUTH_SERVER_URL
  replicas: 1
  selector:
    matchLabels:
      app: employees
--- 
apiVersion: v1
kind: Service
metadata:
  name: employees
  labels:
    app: employees
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30012
  selector:
    app: employees
  type: NodePort
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: employees-config
data:
  KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
