apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-ui # ebből származtatja a deployment, replicaset és pod nevét is
  labels:
    app: employees-ui
spec:
  template: # pod-okat írja le
    metadata:
      name: employees-ui-pod
      labels:
        app: employees-ui
    spec:
      containers:
      - name: employees-ui # pod-on belül egyedi, required
        image: registry.w3pro.net/employees-ui:0.0.1
        ports:
        - containerPort: 8080 # csak tájékoztató jellegű
        env:
        - name: KEYCLOAK_AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: employees-ui-config
              key: KEYCLOAK_AUTH_SERVER_URL
        - name: EMPLOYEES-UI_FRONTEND-URL
          valueFrom:
            configMapKeyRef:
              name: employees-ui-config
              key: EMPLOYEES-UI_FRONTEND-URL
        - name: EMPLOYEES-UI_AUTH-SERVER-FRONTEND-URL
          valueFrom:
            configMapKeyRef:
              name: employees-ui-config
              key: EMPLOYEES-UI_AUTH-SERVER-FRONTEND-URL
        - name: EMPLOYEES-UI_EMPLOYEES-URL
          valueFrom:
            configMapKeyRef:
              name: employees-ui-config
              key: EMPLOYEES-UI_EMPLOYEES-URL
  replicas: 1
  selector: # pod-okat válogatja le
    matchLabels:
      app: employees-ui
--- 
apiVersion: v1
kind: Service
metadata:
  name: employees-ui # Kubernetes DNS ezt adja domain name-nek
  labels:
    app: employees-ui
spec:
  ports:
  - port: 8080
    targetPort: 8080 # target port
    protocol: TCP
    nodePort: 30011
  selector:
    app: employees-ui # pod-okat válogatja le
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: employees-ui-config
data:
  KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
  EMPLOYEES-UI_AUTH-SERVER-FRONTEND-URL: http://keycloak.training:30010/auth
  EMPLOYEES-UI_FRONTEND-URL: http://employees-ui.training:30011
  EMPLOYEES-UI_EMPLOYEES-URL: http://employees:8080/api/employees
