apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_USER: cm9vdA== # root
  KEYCLOAK_PASSWORD: cm9vdA== # root
  MARIADB_USER: a2V5Y2xvYWs= #keycloak
  MARIADB_PASSWORD: a2V5Y2xvYWs= #keycloak  